
/**
 * Security event types for auditing and logging
 */
export enum SecurityEventType {
  // Authentication events
  LOGIN_ATTEMPT = "LOGIN_ATTEMPT",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAILURE = "LOGIN_FAILURE",
  LOGOUT = "LOGOUT",
  PASSWORD_CHANGE = "PASSWORD_CHANGE",
  PASSWORD_RESET_REQUEST = "PASSWORD_RESET_REQUEST",
  
  // Authorization events
  PERMISSION_DENIED = "PERMISSION_DENIED",
  ACCESS_GRANTED = "ACCESS_GRANTED",
  ROLE_CHANGE = "ROLE_CHANGE",
  
  // Session events
  SESSION_CREATED = "SESSION_CREATED",
  SESSION_EXPIRED = "SESSION_EXPIRED",
  SESSION_TERMINATED = "SESSION_TERMINATED",
  SESSION_HIJACK_ATTEMPT = "SESSION_HIJACK_ATTEMPT",
  
  // Token management
  TOKEN_ISSUED = "TOKEN_ISSUED",
  TOKEN_REFRESHED = "TOKEN_REFRESHED",
  TOKEN_REVOKED = "TOKEN_REVOKED",
  TOKEN_REJECTED = "TOKEN_REJECTED",
  
  // API security
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  RATE_LIMIT_WARNING = "RATE_LIMIT_WARNING",
  API_KEY_CREATED = "API_KEY_CREATED",
  API_KEY_REVOKED = "API_KEY_REVOKED",
  
  // Data security
  DATA_EXPORT = "DATA_EXPORT",
  SENSITIVE_DATA_ACCESS = "SENSITIVE_DATA_ACCESS",
  ENCRYPTION_KEY_ROTATION = "ENCRYPTION_KEY_ROTATION",
  
  // Attack detection
  POSSIBLE_XSS_ATTEMPT = "POSSIBLE_XSS_ATTEMPT",
  POSSIBLE_CSRF_ATTEMPT = "POSSIBLE_CSRF_ATTEMPT",
  POSSIBLE_SQL_INJECTION = "POSSIBLE_SQL_INJECTION",
  POSSIBLE_PARAMETER_TAMPERING = "POSSIBLE_PARAMETER_TAMPERING",
  
  // Integration security
  THIRD_PARTY_AUTH = "THIRD_PARTY_AUTH",
  WEBHOOK_DELIVERY_FAILURE = "WEBHOOK_DELIVERY_FAILURE",
  
  // System events
  SECURITY_CONFIGURATION_CHANGE = "SECURITY_CONFIGURATION_CHANGE",
  SECURITY_ALERT = "SECURITY_ALERT"
}
